"""
Core data models for the Vision Bot automation system.
"""
from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class ActionType(str, Enum):
    """Types of actions that can be performed"""
    CLICK = "click"
    TYPE = "type"
    SCROLL = "scroll"
    WAIT = "wait"
    PRESS = "press"
    STOP = "stop"
    HANDLE_SELECT = "handle_select"
    HANDLE_UPLOAD = "handle_upload"
    HANDLE_DATETIME = "handle_datetime"
    BACK = "back"
    FORWARD = "forward"
    OPEN = "open"


class PageSection(str, Enum):
    """Sections of a web page"""
    HEADER = "header"
    CONTENT = "content"
    SIDEBAR = "sidebar"
    MODAL = "modal"
    FOOTER = "footer"


class DetectedElement(BaseModel):
    """A UI element detected in the screenshot"""
    element_label: Optional[str] = Field(default=None, description="The label of the element")
    description: str = Field(description="What this element is (e.g., 'Submit button', 'Email input')")
    element_type: str = Field(description="Type: button, input, link, text, select, upload, date, etc.")
    is_clickable: bool = Field(description="Can this element be clicked?")
    box_2d: List[int] = Field(description="Gemini format: [y_min, x_min, y_max, x_max] normalized 0-1000")
    section: PageSection = Field(description="Which section of the page this is in")
    field_subtype: Optional[str] = Field(default=None, description="For inputs: text, email, password, select, upload, date, etc.")
    confidence: Optional[float] = Field(default=0.5, description="Detection confidence 0.0-1.0")
    requires_special_handling: Optional[bool] = Field(default=False, description="Whether this field requires special multi-step handling")
    overlay_number: Optional[int] = Field(default=None, description="The overlay number from numbered detection system")


class PageElements(BaseModel):
    """A list of detected elements on the page"""
    elements: List[DetectedElement] = Field(description="The list of detected elements")


class ActionStep(BaseModel):
    """A single action to perform"""
    action: ActionType
    overlay_index: Optional[int] = Field(default=None, description="Overlay index of target element from detections")
    x: Optional[int] = Field(default=None, description="X coordinate in pixels")
    y: Optional[int] = Field(default=None, description="Y coordinate in pixels")
    text_to_type: Optional[str] = Field(default=None, description="Text to type (for TYPE action)")
    wait_time_ms: Optional[int] = Field(default=500, description="Time to wait in milliseconds (for WAIT action)")
    scroll_direction: Optional[str] = Field(default="down", description="Scroll direction: up/down")
    keys_to_press: Optional[str] = Field(default=None, description="Keys to press (for PRESS action, e.g., 'enter', 'ctrl+c', 'tab')")
    select_option_text: Optional[str] = Field(default=None, description="Text of option to select (for HANDLE_SELECT)")
    datetime_value: Optional[str] = Field(default=None, description="Date/time value to set (for HANDLE_DATETIME)")
    upload_file_path: Optional[str] = Field(default=None, description="File path to upload (for HANDLE_UPLOAD)")
    url: Optional[str] = Field(default=None, description="URL to open (for OPEN action)")


class VisionPlan(BaseModel):
    """Plan generated by the vision model"""
    detected_elements: PageElements = Field(description="All detected UI elements")
    action_steps: List[ActionStep] = Field(description="Steps to execute")
    reasoning: str = Field(description="Why this plan was chosen")
    confidence: float = Field(description="Overall confidence in this plan", ge=0.0, le=1.0)


class Goal(BaseModel):
    """Goal definition"""
    description: str = Field(description="What we want to achieve")
    target_url_contains: List[str] = Field(default_factory=list, description="URL should contain these strings")
    target_page_text: List[str] = Field(default_factory=list, description="Page should contain this text")
    form_should_be_filled: bool = Field(default=False, description="All required form fields should be filled")


class PageInfo(BaseModel):
    """Information about the current page state"""
    width: int = Field(description="Current page width in pixels")
    height: int = Field(description="Current page height in pixels")
    scroll_x: int = Field(description="Current scroll X position")
    scroll_y: int = Field(description="Current scroll Y position")
    url: str = Field(description="Current page URL")
    title: str = Field(description="Current page title")
    dpr: float = Field(description="Device pixel ratio")
    ss_pixel_w: int = Field(description="Screenshot pixel width")
    ss_pixel_h: int = Field(description="Screenshot pixel height")
    css_scale: float = Field(description="CSS scale")
    doc_width: int = Field(description="Document width in pixels")
    doc_height: int = Field(description="Document height in pixels")
