"""
Consolidated data models for browser-vision-bot.

This module contains all core data models organized by category:
- Core models: ActionType, PageSection, DetectedElement, etc.
- Task models: Task, Sequence, MissionPlan
- Intent models: ActionIntent
"""
from __future__ import annotations

import time
from enum import Enum
from typing import Annotated, Any, Dict, List, Literal, Optional, Union

from pydantic import AliasChoices, BaseModel, ConfigDict, Field


# ============================================================================
# CORE MODELS - Basic types and page elements
# ============================================================================

class ActionType(str, Enum):
    """Types of actions that can be performed"""
    CLICK = "click"
    TYPE = "type"
    SCROLL = "scroll"
    WAIT = "wait"
    PRESS = "press"
    STOP = "stop"
    HANDLE_SELECT = "handle_select"
    HANDLE_UPLOAD = "handle_upload"
    HANDLE_DATETIME = "handle_datetime"
    BACK = "back"
    FORWARD = "forward"
    OPEN = "open"


class PageSection(str, Enum):
    """Sections of a web page"""
    HEADER = "header"
    CONTENT = "content"
    SIDEBAR = "sidebar"
    MODAL = "modal"
    FOOTER = "footer"


class NotebookEntryType(str, Enum):
    """Types of entries stored in the agent notebook"""
    NORMAL_TASK_RESULT = "normal_task_result"
    SEQUENTIAL_TASK_RESULT = "sequential_task_result"
    EXTRACTION = "extraction"
    URL_EXTRACTION = "url_extraction"


class DetectedElement(BaseModel):
    """A UI element detected in the screenshot"""
    element_label: Optional[str] = Field(default=None, description="The label of the element")
    description: str = Field(description="What this element is (e.g., 'Submit button', 'Email input')")
    element_type: str = Field(description="Type: button, input, link, text, select, upload, date, etc.")
    is_clickable: bool = Field(description="Can this element be clicked?")
    box_2d: List[int] = Field(description="Gemini format: [y_min, x_min, y_max, x_max] normalized 0-1000")
    section: PageSection = Field(description="Which section of the page this is in")
    field_subtype: Optional[str] = Field(default=None, description="For inputs: text, email, password, select, upload, date, etc.")
    confidence: Optional[float] = Field(default=0.5, description="Detection confidence 0.0-1.0")
    requires_special_handling: Optional[bool] = Field(default=False, description="Whether this field requires special multi-step handling")
    overlay_number: Optional[int] = Field(default=None, description="The overlay number from numbered detection system")


class PageElements(BaseModel):
    """A list of detected elements on the page"""
    elements: List[DetectedElement] = Field(description="The list of detected elements")


class ActionStep(BaseModel):
    """A single action to perform"""
    action: ActionType
    overlay_index: Optional[int] = Field(default=None, description="Overlay index of target element from detections")
    x: Optional[int] = Field(default=None, description="X coordinate in pixels")
    y: Optional[int] = Field(default=None, description="Y coordinate in pixels")
    text_to_type: Optional[str] = Field(default=None, description="Text to type (for TYPE action)")
    wait_time_ms: Optional[int] = Field(default=500, description="Time to wait in milliseconds (for WAIT action)")
    scroll_direction: Optional[str] = Field(default="down", description="Scroll direction: up/down")
    keys_to_press: Optional[str] = Field(default=None, description="Keys to press (for PRESS action, e.g., 'enter', 'ctrl+c', 'tab')")
    select_option_text: Optional[str] = Field(default=None, description="Text of option to select (for HANDLE_SELECT)")
    datetime_value: Optional[str] = Field(default=None, description="Date/time value to set (for HANDLE_DATETIME)")
    upload_file_path: Optional[str] = Field(default=None, description="File path to upload (for HANDLE_UPLOAD)")
    url: Optional[str] = Field(default=None, description="URL to open (for OPEN action)")


class VisionPlan(BaseModel):
    """Plan generated by the vision model"""
    detected_elements: PageElements = Field(description="All detected UI elements")
    action_steps: List[ActionStep] = Field(description="Steps to execute")
    reasoning: str = Field(description="Why this plan was chosen")
    confidence: float = Field(description="Overall confidence in this plan", ge=0.0, le=1.0)


class Goal(BaseModel):
    """Goal definition"""
    description: str = Field(description="What we want to achieve")
    target_url_contains: List[str] = Field(default_factory=list, description="URL should contain these strings")
    target_page_text: List[str] = Field(default_factory=list, description="Page should contain this text")
    form_should_be_filled: bool = Field(default=False, description="All required form fields should be filled")


class PageInfo(BaseModel):
    """Information about the current page state"""
    width: int = Field(description="Current page width in pixels")
    height: int = Field(description="Current page height in pixels")
    scroll_x: int = Field(description="Current scroll X position")
    scroll_y: int = Field(description="Current scroll Y position")
    url: str = Field(description="Current page URL")
    title: str = Field(description="Current page title")
    dpr: float = Field(description="Device pixel ratio")
    ss_pixel_w: int = Field(description="Screenshot pixel width")
    ss_pixel_h: int = Field(description="Screenshot pixel height")
    css_scale: float = Field(description="CSS scale")
    doc_width: int = Field(description="Document width in pixels")
    doc_height: int = Field(description="Document height in pixels")


# ============================================================================
# TASK MODELS - Mission, Task, and Sequence execution
# ============================================================================

class TaskType(str, Enum):
    """Type of task"""
    NORMAL = "normal"
    SEQUENTIAL = "sequential"


class TaskStatus(str, Enum):
    """Status of task execution"""
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"


class BaseTask(BaseModel):
    """Base class for all task types"""
    task_id: str = Field(default="", description="Unique identifier for this task (auto-generated if empty)")
    type: TaskType = Field(description="Type of task (normal or sequential)")
    description: str = Field(description="Natural language description of what needs to be done")
    status: TaskStatus = Field(default=TaskStatus.PENDING)
    created_at: float = Field(default_factory=time.time, description="Timestamp when task was created")
    completed_at: Optional[float] = Field(default=None, description="Timestamp when task was completed")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata for this task")


class Task(BaseTask):
    """A single executable instruction (formerly NormalTask)"""
    type: Literal[TaskType.NORMAL] = TaskType.NORMAL
    instruction: str = Field(description="The specific instruction to execute (e.g., 'click the login button')")

    depends_on: Optional[str] = Field(
        default=None,
        description="Task ID whose results this task may reference"
    )

    result: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Result of executing this task"
    )
    error: Optional[str] = Field(
        default=None,
        description="Error message if task failed"
    )


class TurnResult(BaseModel):
    """Result of a single turn within a sequence (formerly IterationResult)"""
    turn: int = Field(description="Turn number (0-indexed)")
    status: Literal["success", "failed"] = Field(description="Whether this turn succeeded")
    attempts: int = Field(description="Number of task generation attempts for this turn")
    result: Optional[Any] = Field(default=None, description="Data collected in this turn")
    error: Optional[str] = Field(default=None, description="Error message if failed")
    tasks_attempted: List[str] = Field(
        default_factory=list,
        description="List of task instructions attempted for this turn"
    )


class SequenceState(BaseModel):
    """Tracks progress through a sequence (formerly SequentialState)"""
    current_turn: int = Field(default=0, description="Current turn index")
    turn_attempts: int = Field(default=0, description="Attempts for current turn")
    completed_turns: List[TurnResult] = Field(
        default_factory=list,
        description="History of completed turns"
    )
    total_success_count: int = Field(default=0, description="Number of successful turns")
    total_failure_count: int = Field(default=0, description="Number of failed turns")


class Sequence(BaseTask):
    """A high-level goal requiring multiple turns (formerly SequentialTask)"""
    type: Literal[TaskType.SEQUENTIAL] = TaskType.SEQUENTIAL

    model_config = ConfigDict(populate_by_name=True)

    goal: str = Field(
        description="The overall objective (e.g., 'Extract company names from job listings')",
        validation_alias=AliasChoices("task", "goal"),
    )
    completion_condition: str = Field(
        description="Natural language description of when this sequence is complete"
    )

    target_count: Optional[int] = Field(
        default=None,
        description="Target number of turns (if known upfront). None for indefinite sequences."
    )

    state: SequenceState = Field(default_factory=SequenceState)

    results: List[Any] = Field(
        default_factory=list,
        description="Accumulated results from all turns"
    )

    current_subtask: Optional[str] = Field(
        default=None,
        description="The current task being executed within this sequence"
    )

    extraction_schema: Optional[Dict[str, Any]] = Field(
        default=None,
        description="JSON schema for extraction results, inferred from goal if this is an extraction task"
    )


class MissionPlan(BaseModel):
    """Complete plan of tasks for executing a mission (formerly TaskList)"""
    tasks: List[Annotated[Union[Task, Sequence], Field(discriminator="type")]] = Field(
        description="Ordered list of tasks to execute"
    )
    current_task_index: int = Field(
        default=0,
        description="Index of currently executing task"
    )

    def get_current_task(self) -> Optional[Union[Task, Sequence]]:
        """Get the current task being executed"""
        if 0 <= self.current_task_index < len(self.tasks):
            return self.tasks[self.current_task_index]
        return None

    def get_completed_tasks(self) -> List[Union[Task, Sequence]]:
        """Get all completed tasks"""
        return [t for t in self.tasks if t.status == TaskStatus.COMPLETED]

    def get_pending_tasks(self) -> List[Union[Task, Sequence]]:
        """Get all pending tasks"""
        return [t for t in self.tasks if t.status == TaskStatus.PENDING]

    def advance_to_next_task(self) -> bool:
        """Move to next task, return True if more tasks remain"""
        self.current_task_index += 1
        return self.current_task_index < len(self.tasks)

    def all_tasks_completed(self) -> bool:
        """Check if all tasks have been completed"""
        return all(t.status == TaskStatus.COMPLETED for t in self.tasks)

    def get_task_by_id(self, task_id: str) -> Optional[Union[Task, Sequence]]:
        """Find a task by its ID"""
        for task in self.tasks:
            if task.task_id == task_id:
                return task
        return None


class SequenceDecision(BaseModel):
    """Output of Sequence Planner decision."""
    decision: Literal["generate_task", "end_sequence"] = Field(
        description="What the Sequence Planner decided to do"
    )
    reasoning: str = Field(description="Why this decision was made")

    next_task: Optional[str] = Field(
        default=None,
        description="The specific, grounded task to execute next (if decision == 'generate_task')"
    )

    completion_reason: Optional[str] = Field(
        default=None,
        description="Why the sequence is being ended (if decision == 'end_sequence')"
    )


class MissionPlannerOutput(BaseModel):
    """Output from Mission Planner decomposition (formerly TaskOrchestratorOutput)"""
    tasks: List[Annotated[Union[Task, Sequence], Field(discriminator="type")]] = Field(
        description="Ordered list of tasks decomposed from user request"
    )
    reasoning: str = Field(
        description="Explanation of how the request was decomposed"
    )
    confidence: float = Field(
        default=0.8,
        ge=0.0,
        le=1.0,
        description="Confidence in this decomposition (0.0-1.0)"
    )


# ============================================================================
# INTENT MODELS - Structured action intents
# ============================================================================

class ActionIntent(BaseModel):
    """Structured representation of a user instruction"""

    action: str = Field(description="Verb describing the action (click, type, select, upload, datetime, press, scroll)")
    raw_command: str = Field(description="Original user instruction")

    target_text: Optional[str] = Field(default=None, description="Literal text describing the target element")
    role_hint: Optional[str] = Field(default=None, description="Semantic hint for the element role (button, link, field, etc.)")
    value: Optional[str] = Field(default=None, description="Value associated with the action (text to type, option to select, file path, etc.)")
    helper_text: Optional[str] = Field(default=None, description="Additional contextual helper provided with the command")

    modifiers: Dict[str, str] = Field(default_factory=dict, description="Slot modifiers such as ordinal, region, direction")
    collection_hint: Optional[str] = Field(default=None, description="Grouping hint (list, table, menu, etc.)")
    attribute_filters: Dict[str, str] = Field(default_factory=dict, description="Attribute equals filters (e.g., aria-label)")

    def ordinal(self) -> Optional[int]:
        """Return zero-based ordinal index if available (first -> 0, last -> -1)"""
        raw = self.modifiers.get("ordinal")
        if raw is None:
            return None
        try:
            idx = int(raw)
            return idx
        except ValueError:
            return None

    def normalized_terms(self) -> List[str]:
        """Return key terms for semantic scoring"""
        terms: List[str] = []
        if self.target_text:
            terms.extend(_tokenize(self.target_text))
        if self.role_hint:
            terms.append(self.role_hint.lower())
        for value in self.attribute_filters.values():
            terms.extend(_tokenize(value))
        return list(dict.fromkeys(filter(None, terms)))

    def subject_hint(self) -> Optional[str]:
        if self.role_hint:
            return self.role_hint
        if self.target_text:
            tokens = _tokenize(self.target_text)
            if tokens:
                return tokens[0]
        return None


def _tokenize(text: str) -> List[str]:
    import re
    return [t for t in re.split(r"[^a-z0-9]+", (text or "").lower()) if t]
