"""
Task models for sequential task execution system.

This module defines the data structures for the task-based execution system,
including Normal Tasks (single executable instructions) and Sequential Tasks
(high-level goals requiring iteration).
"""

from typing import Literal, Optional, Dict, Any, List, Union, Annotated
from pydantic import BaseModel, Field
from enum import Enum
import time


class TaskType(str, Enum):
    """Type of task"""
    NORMAL = "normal"
    SEQUENTIAL = "sequential"


class TaskStatus(str, Enum):
    """Status of task execution"""
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"


class BaseTask(BaseModel):
    """Base class for all task types"""
    task_id: str = Field(default="", description="Unique identifier for this task (auto-generated if empty)")
    type: TaskType = Field(description="Type of task (normal or sequential)")
    description: str = Field(description="Natural language description of what needs to be done")
    status: TaskStatus = Field(default=TaskStatus.PENDING)
    created_at: float = Field(default_factory=time.time, description="Timestamp when task was created")
    completed_at: Optional[float] = Field(default=None, description="Timestamp when task was completed")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata for this task")


class NormalTask(BaseTask):
    """A single executable instruction"""
    type: Literal[TaskType.NORMAL] = TaskType.NORMAL
    instruction: str = Field(description="The specific instruction to execute (e.g., 'click the login button')")

    # Optional: link to previous task for result access
    depends_on: Optional[str] = Field(
        default=None,
        description="Task ID whose results this task may reference"
    )

    # Execution result
    result: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Result of executing this task"
    )
    error: Optional[str] = Field(
        default=None,
        description="Error message if task failed"
    )


class IterationResult(BaseModel):
    """Result of a single iteration within a sequential task"""
    iteration: int = Field(description="Iteration number (0-indexed)")
    status: Literal["success", "failed"] = Field(description="Whether this iteration succeeded")
    attempts: int = Field(description="Number of task generation attempts for this iteration")
    result: Optional[Any] = Field(default=None, description="Data collected in this iteration")
    error: Optional[str] = Field(default=None, description="Error message if failed")
    tasks_attempted: List[str] = Field(
        default_factory=list,
        description="List of task instructions attempted for this iteration"
    )


class SequentialState(BaseModel):
    """Tracks progress through a sequential task"""
    current_iteration: int = Field(default=0, description="Current iteration index")
    iteration_attempts: int = Field(default=0, description="Attempts for current iteration")
    completed_iterations: List[IterationResult] = Field(
        default_factory=list,
        description="History of completed iterations"
    )
    total_success_count: int = Field(default=0, description="Number of successful iterations")
    total_failure_count: int = Field(default=0, description="Number of failed iterations")


class SequentialTask(BaseTask):
    """A high-level goal requiring multiple iterations"""
    type: Literal[TaskType.SEQUENTIAL] = TaskType.SEQUENTIAL

    goal: str = Field(description="The overall objective (e.g., 'Extract company names from job listings')")
    completion_condition: str = Field(
        description="Natural language description of when this task is complete"
    )

    # Optional target count for definite sequences
    target_count: Optional[int] = Field(
        default=None,
        description="Target number of iterations (if known upfront). None for indefinite sequences."
    )

    # Sequential state tracking
    state: SequentialState = Field(default_factory=SequentialState)

    # Results accumulator
    results: List[Any] = Field(
        default_factory=list,
        description="Accumulated results from all iterations (includes failures as None or special markers)"
    )

    # Currently executing subtask (generated by Bridge Planner)
    current_subtask: Optional[str] = Field(
        default=None,
        description="The current normal task being executed within this sequence"
    )

    # Extraction schema for validation (auto-generated from goal)
    extraction_schema: Optional[Dict[str, Any]] = Field(
        default=None,
        description="JSON schema for extraction results, inferred from goal if this is an extraction task"
    )


class TaskList(BaseModel):
    """Complete list of tasks for the current session"""
    tasks: List[Annotated[Union[NormalTask, SequentialTask], Field(discriminator="type")]] = Field(
        description="Ordered list of tasks to execute"
    )
    current_task_index: int = Field(
        default=0,
        description="Index of currently executing task"
    )

    def get_current_task(self) -> Optional[Union[NormalTask, SequentialTask]]:
        """Get the current task being executed"""
        if 0 <= self.current_task_index < len(self.tasks):
            return self.tasks[self.current_task_index]
        return None

    def get_completed_tasks(self) -> List[Union[NormalTask, SequentialTask]]:
        """Get all completed tasks"""
        return [t for t in self.tasks if t.status == TaskStatus.COMPLETED]

    def get_pending_tasks(self) -> List[Union[NormalTask, SequentialTask]]:
        """Get all pending tasks"""
        return [t for t in self.tasks if t.status == TaskStatus.PENDING]

    def advance_to_next_task(self) -> bool:
        """Move to next task, return True if more tasks remain"""
        self.current_task_index += 1
        return self.current_task_index < len(self.tasks)

    def all_tasks_completed(self) -> bool:
        """Check if all tasks have been completed"""
        return all(t.status == TaskStatus.COMPLETED for t in self.tasks)

    def get_task_by_id(self, task_id: str) -> Optional[Union[NormalTask, SequentialTask]]:
        """Find a task by its ID"""
        for task in self.tasks:
            if task.task_id == task_id:
                return task
        return None


class BridgePlannerDecision(BaseModel):
    """Output of Bridge Planner decision"""
    decision: Literal["generate_task", "end_sequence"] = Field(
        description="What the Bridge Planner decided to do"
    )
    reasoning: str = Field(description="Why this decision was made")

    # If decision == "generate_task"
    next_task: Optional[str] = Field(
        default=None,
        description="The specific, grounded normal task to execute next"
    )

    # If decision == "end_sequence"
    completion_reason: Optional[str] = Field(
        default=None,
        description="Why the sequence is being ended"
    )


class TaskOrchestratorOutput(BaseModel):
    """Output from Task Orchestrator decomposition"""
    tasks: List[Annotated[Union[NormalTask, SequentialTask], Field(discriminator="type")]] = Field(
        description="Ordered list of tasks decomposed from user request"
    )
    reasoning: str = Field(
        description="Explanation of how the request was decomposed"
    )
    confidence: float = Field(
        default=0.8,
        ge=0.0,
        le=1.0,
        description="Confidence in this decomposition (0.0-1.0)"
    )
